// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using ClassLibrary;
using ClassLibrary.Common.Data;
using System.Data;
using System.Data.OleDb;
using System.Configuration;

namespace ClassLibraryTest
{
	/// <summary>
	///This is a test class for ClassLibrary.List and is intended
	///to contain all ClassLibrary.List Unit Tests
	///</summary>
	[TestClass()]
	public class ListTest
	{
		private TestContext testContextInstance;
		private readonly String m_strConnectionStringName = "appDatabase";

		/// <summary>
		///Gets or sets the test context which provides
		///information about and functionality for the current test run.
		///</summary>
		public TestContext TestContext
		{
			get
			{
				return testContextInstance;
			}
			set
			{
				testContextInstance = value;
			}
		}
		#region Additional test attributes
		// 
		//You can use the following additional attributes as you write your tests:
		//
		//Use ClassInitialize to run code before running the first test in the class
		//
		//[ClassInitialize()]
		//public static void MyClassInitialize(TestContext testContext)
		//{
		//}
		//
		//Use ClassCleanup to run code after all tests in a class have run
		//
		//[ClassCleanup()]
		//public static void MyClassCleanup()
		//{
		//}
		//
		//Use TestInitialize to run code before running each test
		//
		//[TestInitialize()]
		//public void MyTestInitialize()
		//{
		//}
		//
		//Use TestCleanup to run code after each test has run
		//
		//[TestCleanup()]
		//public void MyTestCleanup()
		//{
		//}
		//
		#endregion


		/// <summary>
		///A test for Ends
		///</summary>
		[TestMethod()]
		public void EndsTest()
		{
			List target = new List();

			DateTime val = new DateTime(); 

			target.Ends = val;

			Assert.AreEqual(val, target.Ends, "ClassLibrary.List.Ends was not set correctly.");

			val = new DateTime(2008, 3, 21);

			target.Ends = val;

			Assert.AreEqual(val, target.Ends, "ClassLibrary.List.Ends was not set correctly with a value.");
		}

		/// <summary>
		///A test for GetTable ()
		///</summary>
		[TestMethod()]
		public void GetTableTest()
		{
			List target = new List();

			TableDescription actual;

			actual = target.GetTable();

			
			Assert.AreEqual("ID", actual.Columns[0].Name, "Name is not the same for ID");
			Assert.AreEqual(0,actual.Columns[0].Value,"Value is not the same for ID");
			Assert.AreEqual(DbType.Int32,actual.Columns[0].Type,"Type is not the same for ID");
			Assert.AreEqual(true, actual.Columns[0].IsPrimaryKey,"IsPrimaryKey is not the same for ID");

			Assert.AreEqual("Name", actual.Columns[1].Name, "Name is not the same for Name");
			Assert.AreEqual(null, actual.Columns[1].Value, "Value is not the same for Name");
			Assert.AreEqual(DbType.String, actual.Columns[1].Type, "Type is not the same for Name");
			Assert.AreEqual(false, actual.Columns[1].IsPrimaryKey, "IsPrimaryKey is not the same for Name");

			Assert.AreEqual("Starts", actual.Columns[2].Name, "Name is not the same for Starts");
			Assert.AreEqual(DateTime.MinValue, actual.Columns[2].Value, "Value is not the same for Starts");
			Assert.AreEqual(DbType.DateTime, actual.Columns[2].Type, "Type is not the same for Starts");
			Assert.AreEqual(false, actual.Columns[2].IsPrimaryKey, "IsPrimaryKey is not the same for Starts");

			Assert.AreEqual("Ends", actual.Columns[3].Name, "Name is not the same for Ends");
			Assert.AreEqual(DateTime.MinValue, actual.Columns[3].Value, "Value is not the same for Ends");
			Assert.AreEqual(DbType.DateTime, actual.Columns[3].Type, "Type is not the same for Ends");
			Assert.AreEqual(false, actual.Columns[3].IsPrimaryKey, "IsPrimaryKey is not the same for Ends");

			Assert.AreEqual("WeekList", actual.Columns[4].Name, "Name is not the same for WeekList");
			Assert.AreEqual(false, actual.Columns[4].Value, "Value is not the same for WeekList");
			Assert.AreEqual(DbType.Boolean, actual.Columns[4].Type, "Type is not the same for WeekList");
			Assert.AreEqual(false, actual.Columns[4].IsPrimaryKey, "IsPrimaryKey is not the same for WeekList");
		}

		/// <summary>
		///A test for ID
		///</summary>
		[TestMethod()]
		public void IDTest()
		{
			List target = new List();

			int val = 0; // TODO: Assign to an appropriate value for the property

			target.ID = val;

			Assert.AreEqual(val, target.ID, "ClassLibrary.List.ID was not set correctly.");

			val = 10;

			target.ID = val;

			Assert.AreEqual(val, target.ID, "ClassLibrary.List.ID was not set correctly with a value.");
		}

		/// <summary>
		///A test for List ()
		///</summary>
		[TestMethod()]
		public void ConstructorTest()
		{
			List target = new List();

			Assert.AreEqual(0, target.ID, "ID is not 0.");
			Assert.IsNull(target.Name,"Name is not null.");
			Assert.AreEqual(DateTime.MinValue,target.Starts,"Starts is not DateTime.MinValue.");
			Assert.AreEqual(DateTime.MinValue, target.Ends, "Ends is not DateTime.MinValue.");
			Assert.IsFalse(target.WeekList,"WeekList is true.");
		}

		/// <summary>
		///A test for Load (IDataReader)
		///</summary>
		[TestMethod()]
		public void LoadTest()
		{
			List target = new List();

			DataSet ds = GetDataSet();
			
			target.Load(ds.Tables[0].CreateDataReader());

			Assert.Inconclusive("A method that does not return a value cannot be verified.");
		}

		/// <summary>
		///A test for Name
		///</summary>
		[TestMethod()]
		public void NameTest()
		{
			List target = new List();

			string val = null; // TODO: Assign to an appropriate value for the property

			target.Name = val;


			Assert.AreEqual(val, target.Name, "ClassLibrary.List.Name was not set correctly.");
			Assert.Inconclusive("Verify the correctness of this test method.");
		}

		/// <summary>
		///A test for Starts
		///</summary>
		[TestMethod()]
		public void StartsTest()
		{
			List target = new List();

			DateTime val = new DateTime(); // TODO: Assign to an appropriate value for the property

			target.Starts = val;


			Assert.AreEqual(val, target.Starts, "ClassLibrary.List.Starts was not set correctly.");
			Assert.Inconclusive("Verify the correctness of this test method.");
		}

		/// <summary>
		///A test for WeekList
		///</summary>
		[TestMethod()]
		public void WeekListTest()
		{
			List target = new List();

			bool val = false; // TODO: Assign to an appropriate value for the property

			target.WeekList = val;


			Assert.AreEqual(val, target.WeekList, "ClassLibrary.List.WeekList was not set correctly.");
			Assert.Inconclusive("Verify the correctness of this test method.");
		}

		private DataSet GetDataSet()
		{
			OleDbConnection connection = OpenConnection();

			String strSQL = "select * from List";
			OleDbCommand command = new OleDbCommand(strSQL, connection);
			OleDbDataAdapter adapter = new OleDbDataAdapter(command);

			DataSet ds = new DataSet();

			adapter.Fill(ds);

			connection.Dispose();

			return ds;
		}

		protected OleDbConnection OpenConnection()
		{
			OleDbConnection connection = new OleDbConnection();
			connection.ConnectionString = ConfigurationManager.AppSettings[m_strConnectionStringName].ToString();
			connection.Open();

			return connection;
		}
	}


}
